In [9]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.shape)
arr1.reshape(1,6)

<class 'numpy.ndarray'>
(6,)


array([[1, 2, 3, 4, 5, 6]])

In [17]:
arr2= np.array([[1,2,3,4],[6,7,8,9],[4,6,7,8]])
print(arr2.shape)
print(arr2)

(3, 4)
[[1 2 3 4]
 [6 7 8 9]
 [4 6 7 8]]


In [22]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [ ]:
# Creating one's
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
import pandas as pd